# 网站的基本信息
site:
  tab: WTOTTER的未来空间 # 浏览器标签栏上显示的文本
  title: 💠 WTOTTER's Blog # 网站的标题
  description: 欢迎来到我的未来科技感个人博客！🚀 # 网站的描述
  language: zh # 改成中文
  favicon: /favicon.ico # 网站的图标
  theme: # 浅色和深色模式主题
    light: winter 
    dark: business 
    code: github-dark 
  date_format: YYYY-MM-DD # 日期格式
  blog: 
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home 
      text: 首页 
      href: / 
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: blog
      text: 文章
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
    # 🔴 核心修改点：直接绑定 Hexo 本地预览的绝对超链接！
    - id: butterfly
      text: WTOTTER的后院
      href: "http://localhost:4000/" # ⬅️ 以后你运行 hexo s 时的本地网址，直接带你跳过去！
      svg: "material-symbols:local-florist-outline-rounded"
      target: _blank # ⬅️ 变成在新标签页打开，不影响你当前看 Astro

# 用户的个人信息
user:
  name: WTOTTER 
  site: "https://wtotter.github.io" 
  avatar: /profile.jpg 
  sidebar: # 侧边栏配置
    social:
      - href: "https://github.com/WTOTTER" 
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
  footer: # 页脚配置
    social:
      - href: "https://github.com/WTOTTER"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"